name: flutter_ion
version: 0.2.2
description: Ion SDK for flutter, For live broadcast, video conference, etc., support mobile/deskop/web.
homepage: https://github.com/pion/ion-sdk-flutter
environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  events2: ^0.1.3
  flutter_webrtc: ^0.5.7
  grpc: ^2.8.0
  protobuf: ^1.0.1
  uuid: ^2.0.1
  web_socket_channel: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  test:
