name: flutter_ion
version: 1.0.0
description: Ion SDK for flutter, For live broadcast, video conference, etc., support mobile/deskop/web.
homepage: https://github.com/pion/ion-sdk-flutter
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  events2: ^1.0.0
  flutter_webrtc: ^0.8.9
  grpc: ^3.0.2
  protobuf: ^2.1.0
  sdp_transform: ^0.3.2
  uuid: ^3.0.6
  web_socket_channel: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
  test: ^1.16.8
  
