name: flutter_ion
version: 0.4.0
description: Ion SDK for flutter, For live broadcast, video conference, etc., support mobile/deskop/web.
homepage: https://github.com/pion/ion-sdk-flutter
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  events2: ^1.0.0
  flutter_webrtc: ^0.6.0-nullsafety.0
  grpc: ^3.0.0
  protobuf: ^2.0.0
  uuid: ^3.0.3 
  web_socket_channel: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  test: ^1.6.7
